### ISSUE TITLE
Weird breaking animation

### ISSUE THREAD

**Issue by Razorfin8** [Soartex/Issues#12]
The animation of breaking blocks is the trapdoors cycling.   Kinda game breaking for me

**Comment by artdude543** [comment]
Please, ensure if you're running Fanver on a modded instance that you restart the game after switching RP. This goes for any modded pack in 1.11+ It's a known issue for texture stitching to cache/bug out which leads to incorrect textures being in the mapping.

This, however, is not an issue with Vanilla or something that RP's can fix as it's beyond our control.
