### ISSUE TITLE
No response on contact email regarding licensing questions.

### ISSUE THREAD

**Issue by Guinaro** [Soartex/Issues#13]
I have now sent twice a question regarding licensing towards the provided contact email and have not received any response. (Once a week ago, and once in october 2016 (still waiting on an answer)).

Who do we need to contact to receive a response?

Sinceerly,
Guinaro

**Comment by MoJoCreatior** [comment]
is it a question that can be answered from their licensing page?
[Link](http://lmgtfy.com/?q=Soartex+License)

**Comment by Guinaro** [comment]
No that is the thing. And anyway: they state to contact them if you want to obtain a license. But you get no response.

**Comment by artdude543** [comment]
Heres the deal in regards to this; I have a full-time job along with other needs in the internet world. I'm currently the only person handling the entire pack/emails/support/forums etc... so give us a break eh?

Complaining won't get you anywhere either. Your email will be replied too upon when I get the time to do so; I have other priorities currently and support is not one of them at the moment.

I apologize for the delay.

**Comment by Guinaro** [comment]
I feel sorry for you that it is all coming down to one person to handle everything in a project so large.
Since I am still waiting over a year and a half for a reply on my first e-mail. So I feel that I gave you guys a  very large break already! I strongly recommend you to alter your license terms and not providing a option to obtain a license and removing the contact address. In the license terms it specifically state that those licenses are only valid for 6 months. It is longer than 3 times that time already past my first inquery regarding said license. I can only wonder what people would need to do to actually get a renewal?
Furthermore complaining will indeed get me nowhere, but at least this issue will provide others with a warning that trying to contact a Soartex representative is a futile/wasted effort and obtaining a license is simply impossible.
I hope you find a couple of people who can help you with this project. And otherwise opensource it so that people can actually benefit from the work done so far and won't run into licensing issues.
