### ISSUE TITLE
Thermal Expansion Factorizer Broken Texture

### ISSUE THREAD

**Issue by Silvrus** [Soartex/Issues#19]
Minecraft: 1.12.2
Soartex Universal: Release 1Dec2019
Forge: 14.23.5.2847
ConnectedTexturesMod: 1.0.1.30

Issue: Upon placing down the Factorizer, the front side texture breaks after a second. I checked all other Thermal machines, the Factorizer is the only one that does this.

**Comment by NeosGhost** [comment]
<img width="506" alt="YwjG6UmOm1" src="https://user-images.githubusercontent.com/16095247/75712260-479f7c80-5c8d-11ea-97d5-42b9627b73d7.png">
 
deleting ' - Copy' from the file name fixed it for me.
