### ISSUE TITLE
Missing textures (1.10.2 - Botania, Quark)

### ISSUE THREAD

**Issue by Protheus** [Soartex/Issues#6]
Downloaded the Fanver modded for 1.10.2 and ingame I see in JEI missing textures:

Missing botania mana pool:
![2017-01-05_09 51 35](https://cloud.githubusercontent.com/assets/1455178/21674356/af38de96-d32d-11e6-8300-6f685245091d.png). The texture is still missing when you place the item

also the meta... blocks from botania,; dreamwood, framewood. The spreaders say missing in JEI but when placed are good, severa quark walls;
![2017-01-05_10 09 50](https://cloud.githubusercontent.com/assets/1455178/21674811/b97ac3e0-d32f-11e6-9989-13c1df8bd441.png)

Minecraft oak door:
When in inventory and in hand it has a missing texture. But when the item is placed it is good
![2017-01-05_10 00 28](https://cloud.githubusercontent.com/assets/1455178/21674418/f513be54-d32d-11e6-8eda-65b2ace113e3.png).

**Comment by Shoeboxam** [comment]
Mod model files that inherit from default model files that have been modified by the resource pack tend to break. I actually reorganized all the model files in Invictus last night to fix this. I'm going to port my fixes to Fanver vanilla tonight, and it should address *some* of these issues.

It would be incredibly helpful if you posted your console log- the log contains exception reports that make it much easier to troubleshoot.

Thanks for opening an issue!

**Comment by Protheus** [comment]
You mean the latest.log from the log folder, the file that is 2+ MB ?

**Comment by Protheus** [comment]
Downloaded the latest fanver modded pack (1.10.2) from Curse but missing textures from Botania and Quark:

Mana pool and the Natura Pylons:
![2017-01-14_09 34 11](https://cloud.githubusercontent.com/assets/1455178/21953634/077cb012-da3d-11e6-93c8-45af97d32c95.png)

Quark missing textures in JEI:
![2017-01-14_09 34 54](https://cloud.githubusercontent.com/assets/1455178/21953636/17b0dd78-da3d-11e6-97cf-1c4719a191bd.png)

**Comment by Shoeboxam** [comment]
This was resolved in another thread, and I forgot to close this here.

https://github.com/Soartex-Modded/Modded-1.10.x/issues/30

Thanks for the report!
